version: '3.8'

services:
  api:
    build: .
    container_name: pix-api
    expose:
      - "8080"
    networks:
      - pixnet

  nginx:
    image: nginx:alpine
    container_name: pix-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    networks:
      - pixnet

  certbot:
    image: certbot/certbot
    container_name: pix-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done"
    networks:
      - pixnet

networks:
  pixnet:
    driver: bridge
